name: Deploy to EC2

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master  

jobs:
  build_and_push:
    name: Build and Push Docker Images  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker build -t uka17/envault-api:latest -f Dockerfiles/api .
          docker build -t uka17/envault-service:latest -f Dockerfiles/service .
          docker push uka17/envault-api:latest
          docker push uka17/envault-service:latest

  deploy:
    name: Deploy containers to EC2
    runs-on: ubuntu-latest
    needs: build_and_push 

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/envault
            git pull origin master

            # Refresh images
            docker pull uka17/envault-api:latest
            docker pull uka17/envault-service:latest

            # Restart services
            docker-compose down
            docker-compose up -d --remove-orphans          
