name: Deploy to EC2

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/envault
            git pull origin master

            # Refresh images
            docker pull uka17/envault-api:latest
            docker pull uka17/envault-service:latest

            # Restart services
            docker-compose down
            docker-compose up -d --remove-orphans          
